import appConfigs from '../appConfig';

const appConfig = appConfigs.default;

export const apiUrl = {
    BASE: appConfig.BASE,
    AUTH: appConfig.AUTH,
    FB_CLIENT_ID: appConfig.FB_CLIENT_ID,
    GOOGLE_CLIENT_ID: appConfig.GOOGLE_CLIENT_ID,
    AWS_CONFIG: appConfig.AWS_CONFIG,
    BUCKET_DIR_PARAMS: appConfig.BUCKET_DIR_PARAMS,
    GOOGLE_GEOLOCATION_KEY: appConfig.GOOGLE_GEOLOCATION_KEY,
    GOOGLE_ANALYTICS_KEY: appConfig.GOOGLE_ANALYTICS_KEY,
    authentication: 'auth',
    swaggerLink: 'swagger-ui.html?token=',
    FB_AUTH: 'social/facebook/auth',
    GPLUS_AUTH: 'social/gplus/auth',
    getUserInfo: 'user',
    register: '/register/manual',
    verifyUser: '/register/verifyemail',
    updateProfileImage: '/profileimage',
    updatePassword: '/changepassword',
    forgotPassword: '/forgotpassword',
    validateToken: '/validatetoken',
    resetpassword: '/resetpassword',
    users: 'admin/users',
    tags: 'admin/metatags',
    roles: 'admin/roles',
    user: 'admin/user',
    tag: 'admin/metatag',
    changestatus: '/changestatus',
    updateUser: '/upsert',
    content: 'content',
    actions: 'activity/updateContentState',
    transcodeAction: 'content/action/transcode',
    contents: 'content/search',
    uploadStatus: 'content/uploadstatus',
    metaSuggestion: 'lookup/metatags/suggestion',
    contentType: 'lookup/contentType',
    language: 'lookup/language',
    country: 'lookup/country',
    state: 'lookup/state',
    city: 'lookup/city',
    actionStates: 'lookup/content/state',
    fetchProperty: 'properties',
    languageName: 'content/suggestions',
    languageCategory: 'lookup/category',
    uploadPropertyData: 'property',
    fetchDevice: 'device',
    deviceList: 'device/status/unpair',
    devicePair: 'device/pair/pairingCode',
    deviceUnpair: 'device/unpair',
    videoList: 'videoList',
    propertySearch: 'property/suggestion',
    generatePublicVideoUrl: 'property/generatePublicVideoUrl',
    fetchFilters: 'content/filter',
};
